spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /public/**
  resources:
    add-mappings: true
    cache:
      period: 3600
  datasource:
    url: "jdbc:postgresql://localhost/sbp"
    username: postgres
    driver-class-name: "org.postgresql.Driver"
  sbp:
    runtime-mode: development
    enabled: true
    classes-directories:
      - "out/production/classes"
      - "out/production/resources"
    lib-directories:
      - "libs"
    plugin-properties:
      spring:
        jpa:
          properties:
            hibernate:
              temp:
                use_jdbc_metadata_defaults: false
          database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    controller:
      base-path: sbp
#    custom-plugin-loaders:
#      - demo.sbp.app.CustomPluginLoader
  flyway:
    enabled: true
    schemas:
      - demo_app
    locations: classpath:db_migration
    table: _db_migration
    import-data:
      enabled: true
      location:
        - classpath:seed_data
  jooq:
    sql-dialect: postgres
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        min-pool-size: 5
        borrow-connection-timeout: 60
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl: ERROR
    org.jooq: DEBUG
    org.jooq.Constants: ERROR
    com.atomikos.jdbc.AtomikosConnectionProxy: ERROR

---
spring:
  profiles: docker
  sbp:
    runtime-mode: deployment
    plugins-root: plugins
    plugin-profiles:
      - docker